version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./Server:/app
    networks:
      - app-network

  client-admin:
    container_name: client-admin
    build:
      context: ./client-admin
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network

  client-customer:
    container_name: client-customer
    build:
      context: ./client-customer
    ports:
      - "3002:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
